services:
  frontend:
    build: 
      context: ./requirements/frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./requirements/frontend:/app
    networks:
      - pong_net

networks:
  pong_net:
    name: pong_net
    driver: bridge
